/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PdapButton: typeof import('./src/components/Button/PdapButton.vue')['default']
    PdapContainer: typeof import('./src/components/Container/PdapContainer.vue')['default']
    PdapNav: typeof import('./src/components/Nav/PdapNav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
